/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public final class PrincipalE extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalE() {
        initComponents();
        jPanel1.setSize(550,0);
        Regresar.setSize(0, 0);
        Iconoformulario();
        setTitle("Ventana Trabajadores");
    }
    
       public void Iconoformulario(){ // Este codigo nos pone la imagen que uno seleccione y lo muestra en el formulario y en el icono
           URL url = getClass().getResource("/Imagenes/Logo_Estetica.png");
           ImageIcon icon_frame = new ImageIcon(url);
           setIconImage(icon_frame.getImage());
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Regresar = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Producto = new javax.swing.JLabel();
        Servicio = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(null);

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PNG_251283439616.png"))); // NOI18N
        getContentPane().add(Regresar);
        Regresar.setBounds(0, 10, 90, 80);

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu-circle_icon-icons.com_48264.png"))); // NOI18N
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(10, 10, 80, 72);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/virus_sanitizer_personal_care_products_icon_142216.png"))); // NOI18N

        Servicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/customer-service_icon-icons.com_51012.png"))); // NOI18N
        Servicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ServicioMousePressed(evt);
            }
        });

        Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_theinformation_788.png"))); // NOI18N
        Info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InfoMousePressed(evt);
            }
        });

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit_close_error_15565.png"))); // NOI18N
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Servicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Producto)
                .addGap(41, 41, 41)
                .addComponent(Servicio)
                .addGap(37, 37, 37)
                .addComponent(Info)
                .addGap(42, 42, 42)
                .addComponent(Exit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 270, 550);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_Estetica.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(880, 10, 150, 130);

        setSize(new java.awt.Dimension(1053, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        Thread th = new Thread() 
    {
            
        @Override
        public void run ()
        {
            try
                {
                 for (int a=0;a<=6;a++)
                    {
                    Thread.sleep(50);
                       if (a==1) {jPanel1.setSize(100,550); Menu.setSize(0, 0);Regresar.setSize(100, 100);}
                       if (a==2) {jPanel1.setSize(200,550);}
                       if (a==3) {jPanel1.setSize(300,550);}
                       if (a==4) {jPanel1.setSize(350,550);}
                       
                    }
                } catch (Exception ex)  
                        {
                            System.out.println(ex);   
                        }
        }
    };th.start();
    }//GEN-LAST:event_MenuMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        Thread th = new Thread() 
    {
            
        @Override
        public void run ()
        {
            try
                {
                 for (int a=0;a<=6;a++)
                    {
                    Thread.sleep(50);
                       if (a==1) {jPanel1.setSize(350,550); Regresar.setSize(0,0);}
                       if (a==2) {jPanel1.setSize(300,550);}
                       if (a==3) {jPanel1.setSize(200,550);}
                       if (a==4) {jPanel1.setSize(100,550);}
                       if (a==5) {jPanel1.setSize(0,550);Menu.setSize(75,75);}
                    }
                } catch (Exception ex)  
                        {
                            System.out.println(ex);   
                        }
        }
    };th.start();
    }//GEN-LAST:event_formMousePressed

    private void InfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoMousePressed
        Contacto c = new Contacto();
        c.show();
    }//GEN-LAST:event_InfoMousePressed

    private void ServicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServicioMousePressed
        Servicios s = new Servicios();
        s.show();
    }//GEN-LAST:event_ServicioMousePressed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        Principal P = new Principal();
        P.show();
        dispose();
    }//GEN-LAST:event_ExitMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Regresar;
    private javax.swing.JLabel Servicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
